CREATE DATABASE IF NOT EXISTS `Final Project`;

USE `Final Project`;

CREATE TABLE IF NOT EXISTS T_TAB1 (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GOODS_TYPE VARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    SELLER_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS T_TAB2 (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    AGE INT NOT NULL
);

INSERT IGNORE INTO T_TAB1 (GOODS_TYPE, QUANTITY, AMOUNT, SELLER_NAME) VALUES
('MOBILE PHONE', 2, 400000, 'MIKE'),
('KEYBOARD', 1, 10000, 'MIKE'),
('MOBILE PHONE', 1, 50000, 'JANE'),
('MONITOR', 1, 110000, 'JOE'),
('MONITOR', 2, 80000, 'JANE'),
('MOBILE PHONE', 1, 130000, 'JOE'),
('MOBILE PHONE', 1, 60000, 'ANNA'),
('PRINTER', 1, 90000, 'ANNA'),
('KEYBOARD', 2, 10000, 'ANNA'),
('PRINTER', 1, 80000, 'MIKE');

SELECT * FROM T_TAB1;

INSERT INTO T_TAB2 (NAME, SALARY, AGE) VALUES
('ANNA', 110000, 27),
('JANE', 80000, 25),
('MIKE', 120000, 25),
('JOE', 70000, 24),
('RITA', 120000, 29);

SELECT * FROM T_TAB2;

# Task 1

SELECT DISTINCT GOODS_TYPE FROM T_TAB1;

# Task 2

SELECT 
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM
    T_TAB1
WHERE
    GOODS_TYPE = 'MOBILE PHONE';

# Task 3

SELECT 
    NAME,
    SALARY
FROM
    T_TAB2
WHERE
    SALARY > 100000;
    
# Task 4

SELECT 
    MIN(AGE) AS MIN_AGE,
    MAX(AGE) AS MAX_AGE,
    MIN(SALARY) AS MIN_SALARY,
    MAX(SALARY) AS MAX_SALARY
FROM
    T_TAB2;

# Task 5

SELECT 
    AVG(QUANTITY) AS AVERAGE_QUANTITY
FROM
    T_TAB1
WHERE
    GOODS_TYPE IN ('KEYBOARD', 'PRINTER');

# Task 6

SELECT 
    T_TAB2.NAME AS EMPLOYEE_NAME,
    SUM(T_TAB1.AMOUNT) AS TOTAL_AMOUNT
FROM
    T_TAB1
JOIN T_TAB2 ON T_TAB1.SELLER_NAME = T_TAB2.NAME
GROUP BY
    T_TAB2.NAME;

# Task 7

SELECT 
    T_TAB2.NAME AS EMPLOYEE_NAME,
    T_TAB1.GOODS_TYPE,
    T_TAB1.QUANTITY,
    T_TAB1.AMOUNT,
    T_TAB2.SALARY,
    T_TAB2.AGE
FROM
    T_TAB1
JOIN T_TAB2 ON T_TAB1.SELLER_NAME = T_TAB2.NAME
WHERE
    T_TAB2.NAME = 'MIKE';
    
# Task 8

SELECT 
    NAME,
    AGE
FROM
    T_TAB2
WHERE
    NAME NOT IN (SELECT DISTINCT SELLER_NAME FROM T_TAB1);

# Task 9

SELECT 
    NAME,
    SALARY
FROM
    T_TAB2
WHERE
    AGE < 26;

# Task 10

SELECT
    *
FROM
    T_TAB1 t
JOIN T_TAB2 t2 ON t2.NAME = t.SELLER_NAME
WHERE
    t2.NAME = 'RITA';


